name: Build Release APK

on:
  push:
    branches: [ s2 ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Ensure card_model.dart exists
        run: |
          mkdir -p lib/models
          if [ ! -f lib/models/card_model.dart ]; then
            echo "class CardModel {" > lib/models/card_model.dart
            echo "  final String title;" >> lib/models/card_model.dart
            echo "  bool isFlipped;" >> lib/models/card_model.dart
            echo "  bool isMatched;" >> lib/models/card_model.dart
            echo "" >> lib/models/card_model.dart
            echo "  CardModel({required this.title, this.isFlipped = false, this.isMatched = false});" >> lib/models/card_model.dart
            echo "}" >> lib/models/card_model.dart
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
